name: CI-Pipeline

on:
  pull_request:
    branches: [main]
  # pull_request_target:
  #   types: [opened, closed, synchronize]
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check quality gates
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Install
        run: pnpm i
      - name: Unused
        run: npx lerna exec --stream -- ts-prune src -e
      - name: Format
        if: always()
        run: |
          npx lerna run format
      - name: Lint
        run: |
          npx lerna run lint
      - name: Test
        run: |
          npx lerna run test
      - name: 'Pack'
        run: npx lerna exec --stream -- npm pack
